# Generated by Django 5.1.4 on 2025-01-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='neznámé', max_length=100)),
                ('city', models.CharField(default='neznámé', max_length=100)),
                ('stadium', models.CharField(default='neznámé', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('matches_played', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chance_liga.team')),
            ],
        ),
    ]
