# Generated by Django 5.1.4 on 2025-02-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chance_liga', '0002_alter_chart_matches_played_alter_chart_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(default='neznámé', max_length=50),
        ),
    ]
